"""Streamlit dashboard views — REQ-DASH-001."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st
from athena_sdk import AthenaClient


def render_scan_page(client: AthenaClient) -> None:
    st.header("Daily Scan")
    strategy_path = st.text_input(
        "Strategy YAML", value="../athena-examples/config/ema_crossover.yaml"
    )
    as_of = st.date_input("As-of date", value=date.today())
    symbols_file = st.text_input("Symbols CSV (optional)", value="")
    uploaded = st.file_uploader("Or upload scan JSON", type=["json"])

    if uploaded is not None:
        payload = json.loads(uploaded.getvalue().decode("utf-8"))
        _render_scan_payload(payload)
        return

    if st.button("Run scan", type="primary"):
        with st.spinner("Scanning universe..."):
            try:
                payload = client.scan_dict(
                    strategy_path,
                    as_of,
                    symbols_file=symbols_file or None,
                )
            except Exception as exc:  # noqa: BLE001 — surface user-facing CLI errors in UI
                st.error(str(exc))
                return
        _render_scan_payload(payload)


def _render_scan_payload(payload: dict[str, Any]) -> None:
    st.caption(
        f"As of {payload.get('as_of')} · scanned {payload.get('scanned_count')} · "
        f"filtered {payload.get('filtered_count')}"
    )
    candidates = payload.get("candidates", [])
    if not candidates:
        st.info("No candidates matched the scanner filters.")
        return

    df = pd.DataFrame(candidates)
    display_cols = [
        "symbol",
        "score",
        "breakout_score",
        "rs_score",
        "momentum_score",
        "signal_score",
        "ml_probability",
        "has_entry_signal",
    ]
    st.dataframe(df[[c for c in display_cols if c in df.columns]], use_container_width=True)

    selected = st.selectbox("Inspect candidate", [row["symbol"] for row in candidates])
    row = next(item for item in candidates if item["symbol"] == selected)
    st.subheader(f"{selected} — score {row.get('score')}")
    if row.get("reasons"):
        st.write("**Reasons:**")
        for reason in row["reasons"]:
            st.markdown(f"- {reason}")

    st.write("**Component scores**")
    components = {
        "Breakout": row.get("breakout_score", 0.0),
        "Relative strength": row.get("rs_score", 0.0),
        "Momentum": row.get("momentum_score", 0.0),
        "Signal": row.get("signal_score", 0.0),
    }
    st.bar_chart(pd.Series(components))

    attributions = row.get("ml_attributions") or []
    if attributions:
        st.write("**SHAP feature attributions**")
        attr_df = pd.DataFrame(attributions)
        st.bar_chart(attr_df.set_index("label")["shap_value"])
    elif row.get("ml_rationale"):
        st.info(row["ml_rationale"])


def render_experiments_page(client: AthenaClient) -> None:
    st.header("Experiment Comparison")
    latest = st.number_input("Compare latest N experiments", min_value=2, max_value=50, value=3)
    uploaded = st.file_uploader("Or upload comparison JSON", type=["json"], key="compare_upload")

    if uploaded is not None:
        comparison = json.loads(uploaded.getvalue().decode("utf-8"))
    elif st.button("Load experiments", type="primary"):
        try:
            comparison = client.compare_experiments(latest=int(latest))
        except Exception as exc:  # noqa: BLE001
            st.error(str(exc))
            return
    else:
        st.info("Load experiments from disk or upload a comparison JSON export.")
        return

    experiments = comparison.get("experiments", [])
    if not experiments:
        st.warning("No experiments found.")
        return

    metric_keys = comparison.get("metric_keys", [])
    table = pd.DataFrame(experiments)
    st.dataframe(table, use_container_width=True)

    if metric_keys:
        chart_df = table.set_index("experiment_id")[metric_keys]
        st.line_chart(chart_df.T)


def render_import_page() -> None:
    st.header("Import Artifacts")
    st.markdown(
        "Upload scan or experiment JSON generated by `athena scan --output` or "
        "`athena compare-experiments --output-format json --output`."
    )
    scan_file = st.file_uploader("Scan JSON", type=["json"], key="scan_import")
    if scan_file is not None:
        payload = json.loads(scan_file.getvalue().decode("utf-8"))
        _render_scan_payload(payload)


def main() -> None:
    st.set_page_config(page_title="Athena Dashboard", layout="wide")
    st.title("Athena Dashboard")
    st.caption("Scan results, experiment comparison, and feature importance views")

    with st.sidebar:
        st.subheader("Configuration")
        config_path = st.text_input("Config YAML", value="../athena-examples/config/backtest.yaml")
        profile = st.text_input("Profile (optional)", value="")
        page = st.radio(
            "Page",
            ["Scan", "Experiments", "Import"],
            index=0,
        )

    client = AthenaClient(
        config_path=Path(config_path) if config_path else None,
        profile=profile or None,
    )

    if page == "Scan":
        render_scan_page(client)
    elif page == "Experiments":
        render_experiments_page(client)
    else:
        render_import_page()


if __name__ == "__main__":
    main()
